name: size
on:
  pull_request:
    branches:
      - master

permissions:
  pull-requests: write

jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Size Limit
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ github.token }}
